require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  Exclude:
    - bin/**/*
    - vendor/**/*
    - db/schema.rb
    - tmp/**/*
    - public/**/*

# モデルの削除は現段階では想定していないため、一旦rubocopのチェックをfalseにしておく
Rails/HasManyOrHasOneDependent:
  Enables: false

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 50

Rails/BulkChangeTable:
  Enabled: false


RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 20