'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rails
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          TZ: 'Asia/Tokyo'
        ports:
          - 3306:3306
    env:
      RAILS_ENV: test
      TZ: 'Asia/Tokyo'
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3

    # https://docs.github.com/en/enterprise-cloud@latest/actions/automating-builds-and-tests/building-and-testing-ruby
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: rails

    - name: rubocop
      run: bundle exec rubocop

    - run: bundle exec rails db:create db:migrate
    - name: rspec
      run: bundle exec rspec
    - name: comment to pr
      if: github.event_name == 'pull_request'
      run: |
        PR_ID=$(echo $GITHUB_REF | sed -e 's/[^0-9]//g')
        gh pr comment $PR_ID --body コードカバレッジ:$(cat coverage/.last_run.json | jq .result.line)％
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
